config/routes.rb
Rails.application.routes.draw do
  resources :empresas
  resources :admins
  resources :venta
  resources :compras
  resources :operacions
  resources :cuenta
  resources :clientes

  get '/compras/new/:cuentaid', to: 'compras#new'

  get 'main' => 'main_page#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root :to => "sessions#new"

end

app/models/compra.rb
class Compra < ActiveRecord::Base
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :logged
  before_action :set_cuentaid, only: [:create, :new]
  before_action :set_compra, only: [:show, :edit, :update, :destroy]

  # GET /compras
  # GET /compras.json
  def index
    @compras = Compra.all
  end

  # GET /compras/1
  # GET /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
  end

  # GET /compras/1/edit
  def edit
  end

  # POST /compras
  # POST /compras.json
  def create
    @compra = Compra.new(compra_params)
    @compra.id_cliente = params[:cuentaid]
    respond_to do |format|
      if @compra.save
        format.html { redirect_to @compra, notice: 'Compra was successfully created.' }
        format.json { render :show, status: :created, location: @compra }
      else
        format.html { render :new }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compras/1
  # PATCH/PUT /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to @compra, notice: 'Compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1
  # DELETE /compras/1.json
  def destroy
    @compra.destroy
    respond_to do |format|
      format.html { redirect_to compras_url, notice: 'Compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cuentaid
        @cuenta_id = params[:cuentaid]
    end
    def set_compra
      @compra = Compra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_params
      params.require(:compra).permit(:id_cliente, :cantidad, :tarjeta, :tipo)
    end

    def logged
      unless user_logged_in?
        redirect_to root_url
      end
    end
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/views/compras/_form.html.erb
<%= form_for(@compra) do |f| %>
  <% if @compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compra.errors.count, "error") %> prohibited this compra from being saved:</h2>

      <ul>
      <% @compra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.text_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :tarjeta %><br>
    <%= f.text_field :tarjeta %>
  </div>
  <div class="field">
    <%= f.label "tipo de tarjeta" %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compras/edit.html.erb
<h1>Editing Compra</h1>

<%= render 'form' %>

<%= link_to 'Show', @compra %> |
<%= link_to 'Back', compras_path %>

app/views/compras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Compras</h1>

<table>
  <thead>
    <tr>
      <th>Id cliente</th>
      <th>Cantidad</th>
      <th>Tarjeta</th>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compras.each do |compra| %>
      <tr>
        <td><%= compra.id_cliente %></td>
        <td><%= compra.cantidad %></td>
        <td><%= compra.tarjeta %></td>
        <td><%= compra.tipo %></td>
        <td><%= link_to 'Show', compra %></td>
        <td><%= link_to 'Edit', edit_compra_path(compra) %></td>
        <td><%= link_to 'Destroy', compra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Compra', new_compra_path %>

app/views/compras/new.html.erb
<h1>New Compra</h1>

<%= render 'form' %>

<p><%= params[:cuentaid]%></p>

<%= link_to 'Back', compras_path %>

app/views/compras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id cliente:</strong>
  <%= @compra.id_cliente %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @compra.cantidad %>
</p>

<p>
  <strong>Tarjeta:</strong>
  <%= @compra.tarjeta %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @compra.tipo %>
</p>

<%= link_to 'Edit', edit_compra_path(@compra) %> |
<%= link_to 'Back', compras_path %>