config/routes.rb
Rails.application.routes.draw do
  resources :empresas
  resources :admins
  resources :venta
  resources :compras
  resources :operacions
  resources :cuenta
  resources :clientes

  get '/compras/new/:cuentaid', to: 'compras#new'

  get 'main' => 'main_page#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root :to => "sessions#new"

end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
    before_action :logged
    before_action :set_cuentum, only: [:show, :index]

    def show

    end

    def index
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_cuentum
        @cliente = current_user        
        @q = Cuentum.where(id_usuario: @cliente.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cuentum_params
        params.require(:cuentum).permit(:descripcion, :saldo, :id_usuario)
    end

    def logged
        unless user_logged_in?
            redirect_to root_url
        end
    end
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/main_page/index.html.erb
<nav class="navbar navbar-static-top navbar-dark bg-inverse">
    <a class="navbar-brand" href="#">Project name</a>
    <ul class="nav navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">

            <a class="nav-link" href="#">Contact</a>
        </li>
        <li class="nav-item">
            <%= link_to "Cerrar sesión", logout_path, method: "delete" %>
        </li>
    </ul>
</nav>

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">Hello, <p><%= @cliente.nombre %></p>!</h1>
        <p id="notice"><%= notice %></p>
        <h1>Listing Cuenta</h1>

        <table>
          <thead>
            <tr>
              <th>Id</th>
              <th>Descripcion</th>
              <th>Saldo</th>
              <th>id Usuario</th>
              <th colspan="4"></th>
            </tr>
          </thead>

          <tbody>
            <% @q.each do |cuentum| %>
              <tr>
                <td><%= cuentum.id %></td>
                <td><%= cuentum.descripcion %></td>
                <td><%= cuentum.saldo %></td>
                <td><%= cuentum.id_usuario %></td>
                <td><%= button_to 'Depositar', new_compra_path(cuentum.id), :style => "width:100%;" %></td>
                <td><%= button_to 'Transferir', new_operacion_path,:method => :get, params: { cuentaid: cuentum.id } ,:style => "width:100%;" %></td>
                <td><%= button_to 'Vender', new_ventum_path,:method => :get, params: { cuentaid: cuentum.id } ,:style => "width:100%;" %></td>
                <td><%= link_to 'Destroy', cuentum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%= link_to 'New Cuentum', new_cuentum_path %>
    </div>
</div>

<div class="container">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-4">
            <%= button_to 'Depositar', new_compra_path,:method => :get ,:style => "width:100%;height:500px;" %>
        </div>
        <div class="col-md-4">
            <%= button_to 'Transferir', new_compra_path,:method => :get ,:style => "width:100%;height:500px;" %>
        </div>
        <div class="col-md-4">
            <%= button_to 'Vender', new_ventum_path,:method => :get ,:style => "width:100%;height:500px;" %>
        </div>
    </div>

    <hr>

    <footer>
        <p>&copy; Company 2016</p>
    </footer>
</div> <!-- /container -->

app/views/main_page/show.html.erb
<nav class="navbar navbar-static-top navbar-dark bg-inverse">
    <a class="navbar-brand" href="#">Project name</a>
    <ul class="nav navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
        </li>
    </ul>
</nav>

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">Hello, world!</h1>
        <p id="notice"><%= notice %></p>
        <h1>Listing Cuenta</h1>

        <table>
          <thead>
            <tr>
              <th>Descripcion</th>
              <th>Saldo</th>
              <th>Id usuario</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @cuenta.each do |cuentum| %>
              <tr>
                <td><%= cuentum.descripcion %></td>
                <td><%= cuentum.saldo %></td>
                <td><%= cuentum.id_usuario %></td>
                <td><%= link_to 'Show', cuentum %></td>
                <td><%= link_to 'Edit', edit_cuentum_path(cuentum) %></td>
                <td><%= link_to 'Destroy', cuentum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%= link_to 'New Cuentum', new_cuentum_path %>
    </div>
</div>

<div class="container">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-4">
            <button type="button" name="button"><%= link_to 'New Empresa', new_empresa_path %>cuenta</button>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
    </div>

    <hr>

    <footer>
        <p>&copy; Company 2016</p>
    </footer>
</div> <!-- /container -->